package frc.robot.subsystems.intake;

import java.util.function.BooleanSupplier;

import org.littletonrobotics.junction.Logger;

import edu.wpi.first.networktables.BooleanPublisher;
import edu.wpi.first.networktables.DoublePublisher;
import edu.wpi.first.networktables.NetworkTable;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.networktables.StringPublisher;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import frc.robot.Constants;
import frc.robot.Constants.Intake;

public class IntakeSubsystem extends SubsystemBase {

    // ==== IO Layer ====
    private final IntakeIO io;
    // AutoLogged subclass is generated by @AutoLog on IntakeIOInputs.
    // Using it (not plain IntakeIOInputs) is required for Logger.processInputs() to
    // work.
    private final IntakeIOInputsAutoLogged inputs = new IntakeIOInputsAutoLogged();

    // Tracks roller direction so getIntakeState() doesn't need to poll the IO layer
    private enum RollerState {
        STOPPED, RUNNING, REVERSED
    }

    private RollerState rollerState = RollerState.STOPPED;

    static final double ROLLER_VOLTS = 7.0; // 8.5 was too much

    // ==== Elastic Dashboard Publishers ====
    // Driver-awareness data: state string, slide position, and at-target booleans.
    // Raw motor signals are logged by AK processInputs() — no need to duplicate
    // them here.
    private final NetworkTable intakeTable;
    private final StringPublisher intakeStatePublisher;
    private final DoublePublisher slidePositionPublisher;
    private final BooleanPublisher slideExtendedPublisher;
    private final BooleanPublisher slideRetractedPublisher;

    public IntakeSubsystem(IntakeIO intakeIO) {
        this.io = intakeIO;

        NetworkTableInstance inst = NetworkTableInstance.getDefault();
        intakeTable = inst.getTable("Intake");
        intakeStatePublisher = intakeTable.getStringTopic("State").publish();
        slidePositionPublisher = intakeTable.getDoubleTopic("SlidePosition").publish();
        slideExtendedPublisher = intakeTable.getBooleanTopic("SlideExtended").publish();
        slideRetractedPublisher = intakeTable.getBooleanTopic("SlideRetracted").publish();
    }

    @Override
    public void periodic() {
        io.updateInputs(inputs);
        Logger.processInputs("Intake", inputs);

        // Derived/computed values logged separately so they appear in AdvantageScope
        Logger.recordOutput("Intake/State", getIntakeState());
        Logger.recordOutput("Intake/SlideExtended", isSlideFullyExtended());
        Logger.recordOutput("Intake/SlideRetracted", isSlideFullyRetracted());

        publishTelemetry();
    }

    // Driver-facing telemetry pushed to NetworkTables for Elastic Dashboard.
    private void publishTelemetry() {
        intakeStatePublisher.set(getIntakeState());
        slidePositionPublisher.set(inputs.slidePositionRotations);
        slideExtendedPublisher.set(isSlideFullyExtended());
        slideRetractedPublisher.set(isSlideFullyRetracted());
    }

    // ==== State Queries ====

    /** True when slide is within tolerance of the extended setpoint. */
    public boolean isSlideFullyExtended() {
        return Math.abs(inputs.slidePositionRotations - Constants.Intake.SLIDE_EXTENDED_POSITION) < 0.05;
    }

    /** True when slide is within tolerance of the retracted setpoint. */
    public boolean isSlideFullyRetracted() {
        return Math.abs(inputs.slidePositionRotations - Constants.Intake.SLIDE_RETRACTED_POSITION) < 0.05;
    }

    public String getIntakeState() {
        if (isSlideFullyExtended() && rollerState == RollerState.RUNNING)
            return "Intaking";
        if (isSlideFullyExtended() && rollerState == RollerState.REVERSED)
            return "Ejecting";
        if (isSlideFullyExtended())
            return "Extended";
        if (isSlideFullyRetracted())
            return "Retracted";
        return "Moving";
    }

    // ==== LOW-LEVEL METHODS — called by command factories ====
    // Rule: command factories call these methods, never other command factories.

    // Roller
    public void runRoller() {
        io.setRollerVoltage(ROLLER_VOLTS);
        rollerState = RollerState.RUNNING;
    }

    public void reverseRoller() {
        io.setRollerVoltage(-ROLLER_VOLTS);
        rollerState = RollerState.REVERSED;
    }

    public void stopRoller() {
        io.stopRoller();
        rollerState = RollerState.STOPPED;
    }

    // Slide — MotionMagic position control (motor holds position after command)
    public void extendSlides() {
        io.setSlidePosition(Constants.Intake.SLIDE_EXTENDED_POSITION);
        // intakeState
    }

    public void retractSlides() {
        io.setSlidePosition(Constants.Intake.SLIDE_RETRACTED_POSITION);
    }

    public void retractSlidesSlow() {
        io.setSlidePositionSlow(Constants.Intake.SLIDE_RETRACTED_POSITION);

    }

    public void stopSlide() {
        io.stopSlide();
    }

    // ==== COMMAND FACTORIES ====
    // Rule: build commands from the low-level methods above, never from other
    // commands.

    // ---- Roller commands ----

    /** Runs roller while held; stops on release. */
    public Command intakeRoller() {
        return Commands.startEnd(this::runRoller, this::stopRoller, this)
                .withName("IntakeRoller");
    }

    /** Reverses roller while held; stops on release. */
    public Command reverseIntakeRoller() {
        return Commands.startEnd(this::reverseRoller, this::stopRoller, this)
                .withName("ReverseIntakeRoller");
    }

    // Auton convenience wrappers — build on intakeRoller(), not duplicate logic
    public Command intakeRollerTimer(double seconds) {
        return intakeRoller().withTimeout(seconds);
    }

    public Command intakeRollerUntil(BooleanSupplier condition) {
        return intakeRoller().until(condition);
    }

    // ---- Slide commands ----

    /**
     * Extends slides to the MotionMagic setpoint.
     * Runs once — motor holds position automatically.
     */
    public Command extendSlidesCmd() {
        return Commands.runOnce(this::extendSlides, this)
                .withName("ExtendSlides");
    }

    /**
     * Retracts slides to the MotionMagic setpoint.
     * Runs once — motor holds position automatically.
     */
    public Command retractSlidesCmd() {
        return Commands.runOnce(this::retractSlides, this)
                .withName("RetractSlides");
    }

    public Command retractSlidesSlowCmd() {
        return Commands.runOnce(this::retractSlidesSlow, this)
                .withName("RetractSlidesSlow");
    }
    // ---- Combination commands ----

    /**
     * While button is held:
     * Extend the slides to the full out position.
     * Run the roller while button is held.
     * When button is released:
     * Stop the roller.
     * Slides stay extended (MotionMagic holds them).
     *
     * Implementation: extendSlidesCmd() (runOnce) is confirmed working on hardware.
     * Calling extendSlides() directly inside a startEnd lambda was not working
     * reliably,
     * so this uses a sequence: extend first (completes immediately), then hold
     * roller.
     */
    public Command intakeFuel() {
        return Commands.sequence(
                extendSlidesCmd(),
                Commands.startEnd(this::runRoller, this::stopRoller, this))
                .withName("IntakeFuel");
    }

    /**
     * Autonomous-friendly intake command.
     *
     * Ends via timeout (primary) — the {@code waitForSensor} flag is reserved for
     * future use once a game-piece sensor (e.g. hopper beam-break) is available.
     *
     * Flow:
     *   1. Extends slides to the MotionMagic setpoint (runOnce)
     *   2. Runs the roller for {@code timeoutSeconds} — acts as the end trigger
     *   3. Stops the roller on completion or interrupt
     *   Slides remain extended after the command (MotionMagic holds them).
     *   Call {@link #stopFuel()} or {@link #retractSlidesCmd()} afterward if needed.
     *
     * Typical auton usage:
     * 
     * @return Autonomous intake command
     */
    public Command intakeFuelAuton(double intakeTimeout) {
        return Commands.sequence(
                extendSlidesCmd(),
                Commands.run(this::runRoller, this)
                        .withTimeout(intakeTimeout) // primary end trigger: timeout
                        .finallyDo(this::stopRoller)
        ).withName("IntakeFuelAuton");
    }

    /**
     * Stops roller and retracts slides.
     */
    public Command stopFuel() {
        return Commands.runOnce(
                () -> {
                    stopRoller();
                    retractSlides();
                },
                this)
                .withName("StopFuel");
    }

    // =========================================================================
    // COMPRESS FUEL
    // =========================================================================

    /**
     * Slowly retracts slides over ~2 seconds while continuously running the roller
     * to compress/compact fuel into the hopper.
     *
     * Design: uses {@code Commands.run()} so both the slow-retract setpoint and the
     * roller voltage are re-commanded every loop cycle. A single {@code runOnce}
     * would send the setpoint once and then hold the roller with nothing enforcing
     * DynamicMotionMagic on subsequent ticks — this version avoids that gap.
     *
     * End trigger: {@code withTimeout(timeoutSeconds)} is the primary end trigger.
     * The {@code waitForRetract} flag is reserved for future use (e.g., ending early
     * once {@link #isSlideFullyRetracted()} returns true). Pass {@code false} for now.
     *
     * Non-blocking: the command owns the subsystem requirement but ends on its own
     * after {@code timeoutSeconds}, making it safe to compose with other commands
     * via {@code Commands.parallel()} or as a deadline group in auton.
     *
     * Typical teleop usage (whileTrue):
     * <pre>
     *   operator.leftBumper().whileTrue(intake.compressFuel(2.0, false));
     * </pre>
     *
     *
     * @param timeoutSeconds  How long to run; acts as the primary end trigger.
     *                        ~2.0 s is a good starting point to match slide travel time.
     * @param waitForRetract  Reserved for future use — when true, will end early once
     *                        the slide is fully retracted. Pass {@code false} for now.
     * @return Command that slowly retracts slides while running the roller, ends on timeout
     */
    public Command compressFuel(double timeoutSeconds, boolean waitForRetract) {
        return Commands.run(
                () -> {
                    retractSlidesSlow(); // re-commands DynamicMotionMagic every cycle
                    runRoller();
                }, this)
                .withTimeout(timeoutSeconds) // primary end trigger
                .finallyDo(() -> stopRoller())
                .withName("CompressFuel");
    }

    /* Incremental slide retraction */
    // Slide — incremental retract by 2 rotations, clamped to min position
    public void retractSlidesIncremental() {
        double target = Math.max(inputs.slidePositionRotations - 15.0, Constants.Intake.SLIDE_MIN_POSITION);
        io.setSlidePosition(target);
    }

    public Command retractSlidesIncrementalCmd() {
        return Commands.run(this::retractSlidesIncremental, this)
                .withName("RetractSlidesIncremental");
    }

    public Command compressFuelIncremental() {
        return Commands.startEnd(
                () -> {
                    retractSlidesIncremental();
                    runRoller();
                },
                this::stopRoller,
                this)
                .withName("CompressFuelIncremental");
    }

} // end of class