package frc.robot.subsystems.intake;

import java.util.function.BooleanSupplier;

import org.littletonrobotics.junction.Logger;

import edu.wpi.first.networktables.BooleanPublisher;
import edu.wpi.first.networktables.DoublePublisher;
import edu.wpi.first.networktables.NetworkTable;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.networktables.StringPublisher;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import edu.wpi.first.wpilibj2.command.WaitCommand;
import frc.robot.Constants;
import frc.robot.subsystems.indexer.IndexerSubsystem;

public class IntakeSubsystem extends SubsystemBase {

    // =========================================================================
    // IO LAYER
    // =========================================================================
    private final IntakeIO io;
    // AutoLogged subclass is generated by @AutoLog on IntakeIOInputs.
    // Using it (not plain IntakeIOInputs) is required for Logger.processInputs().
    private final IntakeIOInputsAutoLogged inputs = new IntakeIOInputsAutoLogged();

    // =========================================================================
    // STATE TRACKING
    // =========================================================================

    /**
     * Tracks roller direction internally so getIntakeState() doesn't need to
     * poll the IO layer on every call.
     */
    private enum RollerState {
        STOPPED, RUNNING, REVERSED
    }

    private RollerState rollerState = RollerState.STOPPED;

    // =========================================================================
    // ELASTIC DASHBOARD PUBLISHERS
    // =========================================================================

    // Driver-awareness data: state string, slide position, and at-target booleans.
    // Raw motor signals are captured automatically by CTRE Hoot — no need to
    // duplicate them here.
    private final NetworkTable intakeTable;
    private final StringPublisher intakeStatePublisher;
    private final DoublePublisher slidePositionPublisher;
    private final BooleanPublisher slideExtendedPublisher;
    private final BooleanPublisher slideRetractedPublisher;

    // =========================================================================
    // CONSTRUCTOR
    // =========================================================================
    public IntakeSubsystem(IntakeIO intakeIO) {
        this.io = intakeIO;

        NetworkTableInstance inst = NetworkTableInstance.getDefault();
        intakeTable = inst.getTable("Intake");
        intakeStatePublisher = intakeTable.getStringTopic("State").publish();
        slidePositionPublisher = intakeTable.getDoubleTopic("SlidePosition").publish();
        slideExtendedPublisher = intakeTable.getBooleanTopic("SlideExtended").publish();
        slideRetractedPublisher = intakeTable.getBooleanTopic("SlideRetracted").publish();
    }

    // =========================================================================
    // PERIODIC
    // =========================================================================

    @Override
    public void periodic() {
        io.updateInputs(inputs);
        Logger.processInputs("Intake", inputs);

        // Derived/computed values logged separately so they appear in AdvantageScope
        Logger.recordOutput("Intake/State", getIntakeState());
        Logger.recordOutput("Intake/SlideExtended", isSlideFullyExtended());
        Logger.recordOutput("Intake/SlideRetracted", isSlideFullyRetracted());

        publishTelemetry();
    }

    // Driver-facing telemetry pushed to NetworkTables for Elastic Dashboard.
    private void publishTelemetry() {
        intakeStatePublisher.set(getIntakeState());
        slidePositionPublisher.set(inputs.slidePositionRotations);
        slideExtendedPublisher.set(isSlideFullyExtended());
        slideRetractedPublisher.set(isSlideFullyRetracted());
    }

    // =========================================================================
    // STATE QUERIES  —  read-only, no side effects
    // =========================================================================

    /** True when the roller is actively running forward (intaking). */
    public boolean isRollerRunning() {
        return rollerState == RollerState.RUNNING;
    }

    /** True when slide is within tolerance of the extended setpoint. */
    public boolean isSlideFullyExtended() {
        return Math.abs(inputs.slidePositionRotations - Constants.Intake.SLIDE_EXTENDED_POS) < 0.05;
    }

    /** True when slide is within tolerance of the retracted setpoint. */
    public boolean isSlideFullyRetracted() {
        return Math.abs(inputs.slidePositionRotations - Constants.Intake.SLIDE_RETRACTED_POS) < 0.05;
    }

    public String getIntakeState() {
        if (isSlideFullyExtended() && rollerState == RollerState.RUNNING)
            return "Intaking";
        if (isSlideFullyExtended() && rollerState == RollerState.REVERSED)
            return "Ejecting";
        if (isSlideFullyExtended())
            return "Extended";
        if (isSlideFullyRetracted())
            return "Retracted";
        return "Moving";
    }

    // =========================================================================
    // LOW-LEVEL ACTUATORS  —  called by command factories, never by each other
    // =========================================================================

    // ---- Roller ----    
    
    public void runRoller() {
        io.setRollerVoltage(Constants.Intake.FORWARD_ROLLER_VOLTS);
        rollerState = RollerState.RUNNING;
    }

    public void reverseRoller() {
        io.setRollerVoltage(Constants.Intake.REVERSE_ROLLER_VOLTS);
        rollerState = RollerState.REVERSED;
    }

    public void stopRoller() {
        io.stopRoller();
        rollerState = RollerState.STOPPED;
    }

    // ---- Slide ----
    /** Moves slide to the fully extended position via MotionMagic. Motor holds after. */

    public void extendSlides() {
        io.setSlidePosition(Constants.Intake.SLIDE_EXTENDED_POS);
    }

    /** Moves slide to the fully retracted position via MotionMagic. Motor holds after. */
    public void retractSlides() {
        io.setSlidePosition(Constants.Intake.SLIDE_RETRACTED_POS);
    }

    /**
     * Moves slide to retracted position using the slow DynamicMotionMagic profile.
     * Call this every loop cycle to continuously re-command the slow profile.
     * Used inside Commands.run() blocks for gradual retraction.
     */
    public void retractSlidesSlow() {
        io.setSlidePositionSlow(Constants.Intake.SLIDE_RETRACTED_POS);

    }

    public void stopSlide() {
        io.stopSlide();
    }

    /**
     * Moves slide to an arbitrary position via MotionMagic. Motor holds after.
     * Caller is responsible for clamping to valid range.
     */
    public void setSlidesToPosition(double position) {
        io.setSlidePosition(position);
    }

    /**
     * Retracts slide by 15 rotations from its current position, clamped to the
     * minimum position. Used as a quick incremental jump before slow-finishing.
     */
    public void retractSlidesIncremental() {
        double target = Math.max(inputs.slidePositionRotations - 15.0, Constants.Intake.SLIDE_RETRACTED_POS);
        io.setSlidePosition(target);
    }

    // =========================================================================
    // COMMAND FACTORIES — ROLLER
    // =========================================================================

     /** Runs roller while held; stops on release. */
    public Command intakeRoller() {
        return Commands.startEnd(this::runRoller, this::stopRoller, this)
                .withName("IntakeRoller");
    }

    /** Reverses roller while held; stops on release. */
    public Command reverseIntakeRoller() {
        return Commands.startEnd(this::reverseRoller, this::stopRoller, this)
                .withName("ReverseIntakeRoller");
    }

    // =========================================================================
    // COMMAND FACTORIES — SLIDE
    // =========================================================================

      /**
     * Sends slide to the extended setpoint (runOnce — MotionMagic holds position).
     */
    public Command extendSlidesCmd() {
        return Commands.runOnce(this::extendSlides, this)
                .withName("ExtendSlides");
    }

    /**
     * Sends slide to the retracted setpoint (runOnce — MotionMagic holds position).
     */
    public Command retractSlidesCmd() {
        return Commands.runOnce(this::retractSlides, this)
                .withName("RetractSlides");
    }

    /**
     * Sends slide to the retracted setpoint using the slow profile
     * (runOnce — MotionMagic holds position).
     */
    public Command retractSlidesSlowCmd() {
        return Commands.runOnce(this::retractSlidesSlow, this)
                .withName("RetractSlidesSlow");
    }

    /**
     * Retracts slide by 15 rotations per call. Useful as a single button-tap
     * to nudge the slide back in stages without committing to full retraction.
     */
    public Command retractSlidesIncrementalCmd() {
        return Commands.runOnce(this::retractSlidesIncremental, this)
                .withName("RetractSlidesIncremental");
    }

     // =========================================================================
    // COMMAND FACTORIES — TELEOP COMBINATIONS
    // =========================================================================

    /**
     * Primary teleop intake command. Bind to a button with whileTrue().
     *
     * While held:
     *   1. Extends slides to the full-out setpoint (completes immediately).
     *   2. Runs roller continuously.
     * On release:
     *   - Roller stops. Slides stay extended (MotionMagic holds them).
     *
     * Note: extendSlidesCmd() (runOnce) is used rather than calling extendSlides()
     * directly inside a lambda — the runOnce approach was more reliable on hardware.
     */
    public Command intakeFuel() {
        return Commands.sequence(
                extendSlidesCmd(),
                Commands.startEnd(this::runRoller, this::stopRoller, this))
                .withName("IntakeFuel");
    }

    /**
     * Stops roller and retracts slides in a single action.
     * Bind to a button with onTrue() to cancel intakeFuel() and stow the intake.
     */
    public Command stopFuel() {
        return Commands.runOnce(
                () -> {
                    stopRoller();
                    retractSlides();
                }, this)
                .withName("StopFuel");
    }

    /**
     * Timed compress — slowly retracts slides using the slow DynamicMotionMagic
     * profile while running the roller to compact fuel into the hopper.
     *
     * Ends automatically after {@code timeoutSeconds}. Good for a timed button
     * press where you want the action to finish on its own.
     *
     * Why Commands.run() instead of runOnce():
     * DynamicMotionMagic requires the setpoint to be re-sent every cycle to keep
     * the slow profile active. A single runOnce would only send it once.
     *
     * Typical usage:
     * <pre>
     *   operator.leftBumper().onTrue(intake.compressFuel(2.0));
     * </pre>
     *
     * @param timeoutSeconds How long to run (~2.0 s matches typical slide travel).
     */
    public Command compressFuel(double timeoutSeconds) {
        return Commands.run(
                () -> {
                    retractSlidesSlow();
                    runRoller();
                }, this)
                .withTimeout(timeoutSeconds)
                .finallyDo(() -> stopRoller())
                .withName("CompressFuel");
    }
     
    /**
     * Button-held compress — same slow retraction + roller as compressFuel(),
     * but runs only while the button is held and stops the instant it's released.
     *
     * Use this when you want manual control over how long compression runs.
     * Use compressFuel(seconds) when you want it to self-terminate.
     *
     * Typical usage:
     * <pre>
     *   operator.leftBumper().whileTrue(intake.compressFuelHeld());
     * </pre>
     */
    public Command compressFuelHeld() {
        return Commands.startEnd(
                () -> {
                    retractSlidesIncremental();
                    runRoller();
                },
                this::stopRoller,
                this)
                .withName("CompressFuelHeld");
    }

    /**
     * Workaround: multi-step slide retraction that re-sends the retract setpoint
     * in stages with pauses between each attempt.
     *
     * Background: MotionMagic occasionally fails to complete retraction in a single
     * runOnce call under load. This command re-commands the retracted setpoint four
     * times with 1-second gaps, giving the mechanism time to settle after each push.
     *
     * Status: Still in use as a fallback. If MotionMagic retraction becomes reliable
     * under all conditions, this command can be removed in favor of retractSlidesCmd().
     */
    public Command retractSlidesStack() {
        return Commands.sequence(
                Commands.runOnce(this::retractSlides, this),
                Commands.waitSeconds(1),
                Commands.runOnce(this::retractSlides, this),
                Commands.waitSeconds(1),
                Commands.runOnce(this::retractSlides, this),
                Commands.waitSeconds(1),
                Commands.runOnce(this::retractSlides, this))
                .withName("RetractSlidesStack");
    }

    // =========================================================================
    // COMMAND FACTORIES — Fuel Pump
    // =========================================================================

    /* More involved and current default of agitating the fuel during shooting */
    public Command fuelPump() {
        Timer bounceTimer = new Timer();
        return Commands.run(() -> {
            runRoller();
            if (bounceTimer.get() < 0.5) {
                setSlidesToPosition(Constants.Intake.SLIDE_BOUNCE_DOWN_POS);
            } else if (bounceTimer.get() < 1.0) {
                setSlidesToPosition(Constants.Intake.SLIDE_BOUNCE_UP_POS);
            } else {
                bounceTimer.reset();
            }
        }, this)
                .beforeStarting(() -> {
                    bounceTimer.reset();
                    bounceTimer.start();
                })
                .finallyDo(() -> stopRoller())
                .withName("FuelPump");
    }

    /**
     * Continuously cycles the slides between SLIDE_BOUNCE_DOWN_POS and SLIDE_BOUNCE_UP_POS
     * while running the roller, for as long as the button is held.
     *
     * Use with whileTrue() — the command runs indefinitely and stops cleanly on release.
     * Replaces fuelPumpBasic().repeatedly() which had roller-stop gaps between cycles.
     *
     * Jam recovery: if the slide hasn't reached SLIDE_BOUNCE_UP_POS within 0.5 s of
     * commanding it (physical jam), the cycle immediately restarts to DOWN to dislodge.
     */
    public Command fuelPumpCycle() {
        Timer cycleTimer = new Timer();
        Timer jamTimer = new Timer();
        return Commands.run(() -> {
            runRoller();
            double t = cycleTimer.get();
            if (t < 0.5) {
                setSlidesToPosition(Constants.Intake.SLIDE_BOUNCE_DOWN_POS);
                jamTimer.restart(); // keep resetting so jam timer only counts during UP phase
            } else {
                setSlidesToPosition(Constants.Intake.SLIDE_BOUNCE_UP_POS);
                boolean notNearUp = Math.abs(inputs.slidePositionRotations
                        - Constants.Intake.SLIDE_BOUNCE_UP_POS) > 2.0;
                if (notNearUp && jamTimer.get() >= 0.5) {
                    // Jammed — slide hasn't moved to UP in 0.5 s; restart to DOWN to dislodge
                    cycleTimer.restart();
                    jamTimer.restart();
                } else if (t >= 1.0) {
                    cycleTimer.restart(); // normal end-of-UP-phase reset
                }
            }
        }, this)
                .beforeStarting(() -> { cycleTimer.restart(); jamTimer.restart(); })
                .finallyDo(this::stopRoller)
                .withName("FuelPumpCycle");
    }

    /**
     * Runs the fuel pump cycle (bouncing slides + roller) for a fixed duration.
     * Ends naturally after {@code seconds}, making it safe for autonomous and
     * Choreo event linking via {@code trajectory.atTime("FuelPump").onTrue(...)}.
     *
     * Jam recovery: same as fuelPumpCycle() — if the slide hasn't reached
     * SLIDE_BOUNCE_UP_POS within 0.5 s, the cycle restarts to DOWN to dislodge.
     *
     * @param seconds How long to run the pump cycle.
     */
    public Command fuelPumpCycleAuto(double seconds) {
        Timer cycleTimer = new Timer();
        Timer jamTimer = new Timer();
        return Commands.run(() -> {
            runRoller();
            double t = cycleTimer.get();
            if (t < 0.5) {
                setSlidesToPosition(Constants.Intake.SLIDE_BOUNCE_DOWN_POS);
                jamTimer.restart();
            } else {
                setSlidesToPosition(Constants.Intake.SLIDE_BOUNCE_UP_POS);
                boolean notNearUp = Math.abs(inputs.slidePositionRotations
                        - Constants.Intake.SLIDE_BOUNCE_UP_POS) > 2.0;
                if (notNearUp && jamTimer.get() >= 0.5) {
                    cycleTimer.restart();
                    jamTimer.restart();
                } else if (t >= 1.0) {
                    cycleTimer.restart();
                }
            }
        }, this)
                .beforeStarting(() -> { cycleTimer.restart(); jamTimer.restart(); })
                .withTimeout(seconds)
                .finallyDo(this::stopRoller)
                .withName("FuelPumpCycleAuto");
    }

    /**
     * Sensor-gated fuel pump for autonomous / Choreo event linking.
     *
     * <p>Phase 1 — WAIT (no subsystem held): polls {@code indexer.isFuelDetected()}.
     * While waiting, IntakeSubsystem is free so an {@code intakeFuelTimer} can run
     * in parallel without conflict.
     *
     * <p>Phase 2 — PUMP (claims IntakeSubsystem): bounces slides + runs roller
     * until {@code indexer.isChuteEmpty()} is true (fuel seen then gone for
     * FUEL_CLEAR_TIME seconds).
     *
     * <p>A hard-stop timeout prevents the command from hanging if the sensor lies
     * or fuel never clears.
     *
     * <p>Usage: {@code trajectory.atTime("FuelPump").onTrue(m_intake.fuelPumpCycleSensor(m_indexer));}
     *
     * @param indexer   The IndexerSubsystem that owns the chute CANrange sensor.
     */
    public Command fuelPumpCycleSensor(IndexerSubsystem indexer) {
        Timer cycleTimer = new Timer();
        Timer jamTimer = new Timer();
        return Commands.sequence(
            // Phase 1: wait for first fuel — no subsystem required, intake can run freely
            Commands.runOnce(indexer::resetChuteTracking),
            Commands.waitUntil(indexer::isFuelDetected),
            // Phase 2: pump until chute clears (or hard timeout)
            Commands.run(() -> {
                runRoller();
                double t = cycleTimer.get();
                if (t < 0.5) {
                    setSlidesToPosition(Constants.Intake.SLIDE_BOUNCE_DOWN_POS);
                    jamTimer.restart();
                } else {
                    setSlidesToPosition(Constants.Intake.SLIDE_PUMP_SENSOR_UP_POS);
                    boolean notNearUp = Math.abs(inputs.slidePositionRotations
                            - Constants.Intake.SLIDE_PUMP_SENSOR_UP_POS) > 2.0;
                    if (notNearUp && jamTimer.get() >= 0.5) {
                        cycleTimer.restart();
                        jamTimer.restart();
                    } else if (t >= 1.0) {
                        cycleTimer.restart();
                    }
                }
            }, this)
                .beforeStarting(() -> { cycleTimer.restart(); jamTimer.restart(); })
                .until(indexer::isChuteEmpty)
                .withTimeout(10.0) // hard stop — tune or remove once reliable
        )
        .finallyDo(this::stopRoller)
        .withName("FuelPumpCycleSensor");
    }

    // Loopable and repeatable version of fuelPump() for more manual control over timing and cycles.
    public Command fuelPumpBasic() {
        return Commands.sequence(
                Commands.run(() -> {
                    runRoller();
                    setSlidesToPosition(Constants.Intake.SLIDE_BOUNCE_DOWN_POS);
                }, this)
                        .withTimeout(0.5),
                Commands.run(() -> {
                    runRoller();
                    setSlidesToPosition(Constants.Intake.SLIDE_BOUNCE_UP_POS);
                }, this)
                        .withTimeout(0.5))
                .finallyDo(this::stopRoller).withName("FuelPumpBasic");
    }

    // Ideally set up to take an argument for number of cycles, but for now just a quick test of multiple repeats of the basic bounce sequence.
    public Command fuelPumpSetCycles() {
        return Commands.sequence(
                // ==== Cycle 1 ====
                Commands.run(() -> {
                    runRoller();
                    setSlidesToPosition(Constants.Intake.SLIDE_BOUNCE_DOWN_POS);
                }, this)
                        .withTimeout(0.5),
                // Short pause between down and up to allow fuel to settle before bouncing back up again
                Commands.waitSeconds(0.1),
                Commands.run(() -> {
                    runRoller();
                    setSlidesToPosition(Constants.Intake.SLIDE_BOUNCE_UP_POS);
                }, this)
                    .withTimeout(0.5),
                Commands.waitSeconds(0.1),

                // ==== Cycle 2 ====
                Commands.run(() -> {
                    runRoller();
                    setSlidesToPosition(Constants.Intake.SLIDE_BOUNCE_DOWN_POS);
                }, this)
                        .withTimeout(0.5),
                Commands.waitSeconds(0.1),
                Commands.run(() -> {
                    runRoller();
                    setSlidesToPosition(Constants.Intake.SLIDE_BOUNCE_UP_POS);
                }, this)
                        .withTimeout(0.5),
                Commands.waitSeconds(0.1)


                .finallyDo(this::stopRoller).withName("FuelPumpBasic"));
    }

    // Notable that this one is missing roller commands
    public Command fuelPumpSetCyclesRetract() {
        return Commands.sequence(
                // ==== Cycle 1 ====
                Commands.runOnce(() -> setSlidesToPosition(Constants.Intake.SLIDE_BOUNCE_DOWN_POS), this),
                Commands.waitSeconds(0.5),
                Commands.runOnce(() -> setSlidesToPosition(Constants.Intake.SLIDE_BOUNCE_UP_POS), this),
                Commands.waitSeconds(0.5),
                // ==== Cycle 2 ====
                Commands.runOnce(() -> setSlidesToPosition(Constants.Intake.SLIDE_BOUNCE_DOWN_POS), this),
                Commands.waitSeconds(0.5),
                Commands.runOnce(() -> setSlidesToPosition(Constants.Intake.SLIDE_BOUNCE_UP_POS), this),
                Commands.waitSeconds(0.5),
                // ==== Cycle 3 ====
                Commands.runOnce(() -> setSlidesToPosition(Constants.Intake.SLIDE_RETRACTED_POS), this))
                .withName("FuelPumpThenRetractSlide");
    }
    // =========================================================================
    // COMMAND FACTORIES — AUTONOMOUS
    // =========================================================================

    /**
     * Auton roller — runs for a fixed number of seconds.
     * Shorthand for intakeRoller().withTimeout(seconds).
     *
     * @param seconds Duration to run the roller.
     */
    public Command intakeRollerTimer(double seconds) {
        return intakeRoller().withTimeout(seconds)
                .withName("IntakeRollerTimer");
    }

    /**
     * Auton roller — runs until a sensor condition is met (e.g. hopper full).
     *
     * @param condition BooleanSupplier that returns true when the roller should stop.
     */
    public Command intakeRollerUntil(BooleanSupplier condition) {
        return intakeRoller().until(condition)
                .withName("IntakeRollerUntil");
    }

    /**
     * Full auton intake sequence.
     *
     * Flow:
     *   1. Extends slides to the MotionMagic setpoint (runOnce).
     *   2. Runs roller for {@code intakeTimeout} seconds.
     *   3. Stops roller on completion or interruption.
     *
     * Slides remain extended after the command — call stopFuel() or
     * retractSlidesCmd() afterward if stowing is needed.
     *
     * @param intakeTimeout How long to run the roller after extending.
     */
    public Command intakeFuelTimer(double intakeTimeout) {
        return Commands.sequence(
                extendSlidesCmd(),
                Commands.run(this::runRoller, this)
                        .withTimeout(intakeTimeout)
                        .finallyDo(this::stopRoller))
                .withName("IntakeFuelAuton");
    }

    public Command intakeFuelUntil(BooleanSupplier condition) {
        return Commands.sequence(
                extendSlidesCmd(),
                Commands.run(this::runRoller, this)
                        .until(condition)
                        .finallyDo(this::stopRoller))
                .withName("IntakeFuelAuton");
    }

    /**
     * Two-phase retraction with roller running — designed to be used as the
     * non-deadline side of a Commands.deadline() alongside a shoot sequence.
     *
     * Phase 1 (runOnce): Quick 15-rotation jump back via normal MotionMagic.
     *                    Roller starts here.
     * Phase 2 (run loop): Slow DynamicMotionMagic finish to SLIDE_RETRACTED_POS,
     *                     re-commanded every cycle until isSlideFullyRetracted().
     *
     * Roller is stopped in finallyDo so any interrupt (e.g. deadline finishing)
        * still cleans up properly.
        *
     * Typical auton usage:
     * <pre>
     *   Commands.deadline(
     *       FuelCommands.shootWithPreset(shooter, indexer, rpm, hood),
     *       intake.retractSlidesWithRollerCmd());
     * </pre>
     */
    public Command retractSlidesAuton() {
        return Commands.sequence(
                Commands.runOnce(() -> {
                    retractSlidesIncremental();
                    runRoller();
                }, this),
                Commands.run(() -> {
                    retractSlidesSlow();
                    runRoller();
                }, this).until(this::isSlideFullyRetracted))
                .finallyDo(() -> stopRoller())
                .withName("RetractSlidesWithRoller");
    }

} // end of class