package frc.robot.subsystems.led;

/* Generated by Phoenix Tuner X */

import static edu.wpi.first.units.Units.*;

import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import frc.robot.Constants;

import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.controls.LarsonAnimation;
import com.ctre.phoenix6.controls.SolidColor;
import com.ctre.phoenix6.hardware.CANdle;
import com.ctre.phoenix6.signals.LarsonBounceValue;
import com.ctre.phoenix6.signals.RGBWColor;

@SuppressWarnings("unused") // Suppress warnings for unused right now

/**
 * Subsystem that controls an addressable LED strip using a CANdle.
 */
public class LedSubsystem_CANDLE_only extends SubsystemBase {
    private final CANdle m_candle = new CANdle(Constants.Led.CANDLE_ID, Constants.RIO_CANBUS);

    // // == Preset Colors ==
    // private static final LedColor IDLE_COLOR = new LedColor(0, 0, 0);
    // private static final LedColor SPINUP_COLOR = new LedColor(255, 140, 0); // Orange
    // private static final LedColor READY_COLOR = new LedColor(0, 255, 0); // Green
    // private static final LedColor PASS_COLOR = new LedColor(0, 0, 255); // Blue
    // private static final LedColor EJECT_COLOR = new LedColor(255, 0, 0); // Red

    private final LarsonAnimation m_slot0Animation = new LarsonAnimation(0, 8)
        .withSlot(0)
        .withColor(new RGBWColor(255, 0, 0, 0))
        .withSize(1)
        .withBounceMode(LarsonBounceValue.Front)
        .withFrameRate(Hertz.of(10));

    private final SolidColor[] m_colors = new SolidColor[] {
    };

    // private final int ledCount;

    // private LedColor lastColor = IDLE_COLOR;

    public LedSubsystem_CANDLE_only() {
        setDefaultCommand(updateLEDs());
    }

    /**
     * Updates the animations and LEDs of the CANdle.
     *
     * @return Command to run
     */
    public Command updateLEDs() {
        return run(() -> {
            for (var solidColor : m_colors) {
                m_candle.setControl(solidColor);
            }
            m_candle.setControl(m_slot0Animation);
        });
    }
}
